`default_nettype none

// Functional test wrapper for the AXIL_S_IO_W supertile: AXIL_S_BEL at its
// master tile, looped back through axil_s_loopback.
// Test/axil_s_loopback_tb.v checks it from the SoC side.
module axil_s_loopback_top;
    wire [66:0] o;
    wire [40:0] i;

    axil_s_loopback logic_i (.o(o), .i(i));

    (* keep, BEL="X0Y16.A" *) AXIL_S_BEL axil_s_i (
        .FAB_AWADDR0(o[0]),
        .FAB_AWADDR1(o[1]),
        .FAB_AWADDR2(o[2]),
        .FAB_AWADDR3(o[3]),
        .FAB_AWADDR4(o[4]),
        .FAB_AWADDR5(o[5]),
        .FAB_AWADDR6(o[6]),
        .FAB_AWADDR7(o[7]),
        .FAB_AWADDR8(o[8]),
        .FAB_AWADDR9(o[9]),
        .FAB_AWPROT0(o[10]),
        .FAB_AWPROT1(o[11]),
        .FAB_AWPROT2(o[12]),
        .FAB_AWVALID(o[13]),
        .FAB_WDATA0(o[14]),
        .FAB_WDATA1(o[15]),
        .FAB_WDATA2(o[16]),
        .FAB_WDATA3(o[17]),
        .FAB_WDATA4(o[18]),
        .FAB_WDATA5(o[19]),
        .FAB_WDATA6(o[20]),
        .FAB_WDATA7(o[21]),
        .FAB_WDATA8(o[22]),
        .FAB_WDATA9(o[23]),
        .FAB_WDATA10(o[24]),
        .FAB_WDATA11(o[25]),
        .FAB_WDATA12(o[26]),
        .FAB_WDATA13(o[27]),
        .FAB_WDATA14(o[28]),
        .FAB_WDATA15(o[29]),
        .FAB_WDATA16(o[30]),
        .FAB_WDATA17(o[31]),
        .FAB_WDATA18(o[32]),
        .FAB_WDATA19(o[33]),
        .FAB_WDATA20(o[34]),
        .FAB_WDATA21(o[35]),
        .FAB_WDATA22(o[36]),
        .FAB_WDATA23(o[37]),
        .FAB_WDATA24(o[38]),
        .FAB_WDATA25(o[39]),
        .FAB_WDATA26(o[40]),
        .FAB_WDATA27(o[41]),
        .FAB_WDATA28(o[42]),
        .FAB_WDATA29(o[43]),
        .FAB_WDATA30(o[44]),
        .FAB_WDATA31(o[45]),
        .FAB_WSTRB0(o[46]),
        .FAB_WSTRB1(o[47]),
        .FAB_WSTRB2(o[48]),
        .FAB_WSTRB3(o[49]),
        .FAB_WVALID(o[50]),
        .FAB_BREADY(o[51]),
        .FAB_ARADDR0(o[52]),
        .FAB_ARADDR1(o[53]),
        .FAB_ARADDR2(o[54]),
        .FAB_ARADDR3(o[55]),
        .FAB_ARADDR4(o[56]),
        .FAB_ARADDR5(o[57]),
        .FAB_ARADDR6(o[58]),
        .FAB_ARADDR7(o[59]),
        .FAB_ARADDR8(o[60]),
        .FAB_ARADDR9(o[61]),
        .FAB_ARPROT0(o[62]),
        .FAB_ARPROT1(o[63]),
        .FAB_ARPROT2(o[64]),
        .FAB_ARVALID(o[65]),
        .FAB_RREADY(o[66]),
        .FAB_AWREADY(i[0]),
        .FAB_WREADY(i[1]),
        .FAB_BRESP0(i[2]),
        .FAB_BRESP1(i[3]),
        .FAB_BVALID(i[4]),
        .FAB_ARREADY(i[5]),
        .FAB_RDATA0(i[6]),
        .FAB_RDATA1(i[7]),
        .FAB_RDATA2(i[8]),
        .FAB_RDATA3(i[9]),
        .FAB_RDATA4(i[10]),
        .FAB_RDATA5(i[11]),
        .FAB_RDATA6(i[12]),
        .FAB_RDATA7(i[13]),
        .FAB_RDATA8(i[14]),
        .FAB_RDATA9(i[15]),
        .FAB_RDATA10(i[16]),
        .FAB_RDATA11(i[17]),
        .FAB_RDATA12(i[18]),
        .FAB_RDATA13(i[19]),
        .FAB_RDATA14(i[20]),
        .FAB_RDATA15(i[21]),
        .FAB_RDATA16(i[22]),
        .FAB_RDATA17(i[23]),
        .FAB_RDATA18(i[24]),
        .FAB_RDATA19(i[25]),
        .FAB_RDATA20(i[26]),
        .FAB_RDATA21(i[27]),
        .FAB_RDATA22(i[28]),
        .FAB_RDATA23(i[29]),
        .FAB_RDATA24(i[30]),
        .FAB_RDATA25(i[31]),
        .FAB_RDATA26(i[32]),
        .FAB_RDATA27(i[33]),
        .FAB_RDATA28(i[34]),
        .FAB_RDATA29(i[35]),
        .FAB_RDATA30(i[36]),
        .FAB_RDATA31(i[37]),
        .FAB_RRESP0(i[38]),
        .FAB_RRESP1(i[39]),
        .FAB_RVALID(i[40])
    );
endmodule
`resetall
