`default_nettype none

// Functional test wrapper for the AXI_M_IO_W supertile: AXI_M_BEL at its
// master tile with three tie-offs enabled, looped back through
// axi_m_loopback. Test/axi_m_loopback_tb.v checks it from the SoC side.
module axi_m_loopback_top;
    wire [31:0] rd, wdata, awaddr, araddr;
    wire [9:0]  c;
    wire [45:0] ctrl;

    axi_m_loopback logic_i (.rd(rd), .c(c), .wdata(wdata), .awaddr(awaddr),
                            .araddr(araddr), .ctrl(ctrl));

    (* keep, BEL="X0Y10.A" *) AXI_M_BEL #(.TIE_OFF_WSTRB(1), .TIE_OFF_ARSIZE(1), .TIE_OFF_AWCACHE(1)) axi_m_i (
        .FAB_RDATA0(rd[0]),
        .FAB_WDATA0(wdata[0]),
        .FAB_AWADDR0(awaddr[0]),
        .FAB_ARADDR0(araddr[0]),
        .FAB_RDATA1(rd[1]),
        .FAB_WDATA1(wdata[1]),
        .FAB_AWADDR1(awaddr[1]),
        .FAB_ARADDR1(araddr[1]),
        .FAB_RDATA2(rd[2]),
        .FAB_WDATA2(wdata[2]),
        .FAB_AWADDR2(awaddr[2]),
        .FAB_ARADDR2(araddr[2]),
        .FAB_RDATA3(rd[3]),
        .FAB_WDATA3(wdata[3]),
        .FAB_AWADDR3(awaddr[3]),
        .FAB_ARADDR3(araddr[3]),
        .FAB_RDATA4(rd[4]),
        .FAB_WDATA4(wdata[4]),
        .FAB_AWADDR4(awaddr[4]),
        .FAB_ARADDR4(araddr[4]),
        .FAB_RDATA5(rd[5]),
        .FAB_WDATA5(wdata[5]),
        .FAB_AWADDR5(awaddr[5]),
        .FAB_ARADDR5(araddr[5]),
        .FAB_RDATA6(rd[6]),
        .FAB_WDATA6(wdata[6]),
        .FAB_AWADDR6(awaddr[6]),
        .FAB_ARADDR6(araddr[6]),
        .FAB_RDATA7(rd[7]),
        .FAB_WDATA7(wdata[7]),
        .FAB_AWADDR7(awaddr[7]),
        .FAB_ARADDR7(araddr[7]),
        .FAB_RDATA8(rd[8]),
        .FAB_WDATA8(wdata[8]),
        .FAB_AWADDR8(awaddr[8]),
        .FAB_ARADDR8(araddr[8]),
        .FAB_RDATA9(rd[9]),
        .FAB_WDATA9(wdata[9]),
        .FAB_AWADDR9(awaddr[9]),
        .FAB_ARADDR9(araddr[9]),
        .FAB_RDATA10(rd[10]),
        .FAB_WDATA10(wdata[10]),
        .FAB_AWADDR10(awaddr[10]),
        .FAB_ARADDR10(araddr[10]),
        .FAB_RDATA11(rd[11]),
        .FAB_WDATA11(wdata[11]),
        .FAB_AWADDR11(awaddr[11]),
        .FAB_ARADDR11(araddr[11]),
        .FAB_RDATA12(rd[12]),
        .FAB_WDATA12(wdata[12]),
        .FAB_AWADDR12(awaddr[12]),
        .FAB_ARADDR12(araddr[12]),
        .FAB_RDATA13(rd[13]),
        .FAB_WDATA13(wdata[13]),
        .FAB_AWADDR13(awaddr[13]),
        .FAB_ARADDR13(araddr[13]),
        .FAB_RDATA14(rd[14]),
        .FAB_WDATA14(wdata[14]),
        .FAB_AWADDR14(awaddr[14]),
        .FAB_ARADDR14(araddr[14]),
        .FAB_RDATA15(rd[15]),
        .FAB_WDATA15(wdata[15]),
        .FAB_AWADDR15(awaddr[15]),
        .FAB_ARADDR15(araddr[15]),
        .FAB_RDATA16(rd[16]),
        .FAB_WDATA16(wdata[16]),
        .FAB_AWADDR16(awaddr[16]),
        .FAB_ARADDR16(araddr[16]),
        .FAB_RDATA17(rd[17]),
        .FAB_WDATA17(wdata[17]),
        .FAB_AWADDR17(awaddr[17]),
        .FAB_ARADDR17(araddr[17]),
        .FAB_RDATA18(rd[18]),
        .FAB_WDATA18(wdata[18]),
        .FAB_AWADDR18(awaddr[18]),
        .FAB_ARADDR18(araddr[18]),
        .FAB_RDATA19(rd[19]),
        .FAB_WDATA19(wdata[19]),
        .FAB_AWADDR19(awaddr[19]),
        .FAB_ARADDR19(araddr[19]),
        .FAB_RDATA20(rd[20]),
        .FAB_WDATA20(wdata[20]),
        .FAB_AWADDR20(awaddr[20]),
        .FAB_ARADDR20(araddr[20]),
        .FAB_RDATA21(rd[21]),
        .FAB_WDATA21(wdata[21]),
        .FAB_AWADDR21(awaddr[21]),
        .FAB_ARADDR21(araddr[21]),
        .FAB_RDATA22(rd[22]),
        .FAB_WDATA22(wdata[22]),
        .FAB_AWADDR22(awaddr[22]),
        .FAB_ARADDR22(araddr[22]),
        .FAB_RDATA23(rd[23]),
        .FAB_WDATA23(wdata[23]),
        .FAB_AWADDR23(awaddr[23]),
        .FAB_ARADDR23(araddr[23]),
        .FAB_RDATA24(rd[24]),
        .FAB_WDATA24(wdata[24]),
        .FAB_AWADDR24(awaddr[24]),
        .FAB_ARADDR24(araddr[24]),
        .FAB_RDATA25(rd[25]),
        .FAB_WDATA25(wdata[25]),
        .FAB_AWADDR25(awaddr[25]),
        .FAB_ARADDR25(araddr[25]),
        .FAB_RDATA26(rd[26]),
        .FAB_WDATA26(wdata[26]),
        .FAB_AWADDR26(awaddr[26]),
        .FAB_ARADDR26(araddr[26]),
        .FAB_RDATA27(rd[27]),
        .FAB_WDATA27(wdata[27]),
        .FAB_AWADDR27(awaddr[27]),
        .FAB_ARADDR27(araddr[27]),
        .FAB_RDATA28(rd[28]),
        .FAB_WDATA28(wdata[28]),
        .FAB_AWADDR28(awaddr[28]),
        .FAB_ARADDR28(araddr[28]),
        .FAB_RDATA29(rd[29]),
        .FAB_WDATA29(wdata[29]),
        .FAB_AWADDR29(awaddr[29]),
        .FAB_ARADDR29(araddr[29]),
        .FAB_RDATA30(rd[30]),
        .FAB_WDATA30(wdata[30]),
        .FAB_AWADDR30(awaddr[30]),
        .FAB_ARADDR30(araddr[30]),
        .FAB_RDATA31(rd[31]),
        .FAB_WDATA31(wdata[31]),
        .FAB_AWADDR31(awaddr[31]),
        .FAB_ARADDR31(araddr[31]),
        .FAB_AWREADY(c[0]),
        .FAB_WREADY(c[1]),
        .FAB_BRESP0(c[2]),
        .FAB_BRESP1(c[3]),
        .FAB_BVALID(c[4]),
        .FAB_ARREADY(c[5]),
        .FAB_RRESP0(c[6]),
        .FAB_RRESP1(c[7]),
        .FAB_RLAST(c[8]),
        .FAB_RVALID(c[9]),
        .FAB_AWLEN0(ctrl[0]),
        .FAB_AWLEN1(ctrl[1]),
        .FAB_AWLEN2(ctrl[2]),
        .FAB_AWLEN3(ctrl[3]),
        .FAB_AWLEN4(ctrl[4]),
        .FAB_AWLEN5(ctrl[5]),
        .FAB_AWLEN6(ctrl[6]),
        .FAB_AWLEN7(ctrl[7]),
        .FAB_AWSIZE0(ctrl[8]),
        .FAB_AWSIZE1(ctrl[9]),
        .FAB_AWSIZE2(ctrl[10]),
        .FAB_AWBURST0(ctrl[11]),
        .FAB_AWBURST1(ctrl[12]),
        .FAB_AWLOCK(ctrl[13]),
        .FAB_AWCACHE0(ctrl[14]),
        .FAB_AWCACHE1(ctrl[15]),
        .FAB_AWCACHE2(ctrl[16]),
        .FAB_AWCACHE3(ctrl[17]),
        .FAB_AWVALID(ctrl[18]),
        .FAB_WSTRB0(ctrl[19]),
        .FAB_WSTRB1(ctrl[20]),
        .FAB_WSTRB2(ctrl[21]),
        .FAB_WSTRB3(ctrl[22]),
        .FAB_WLAST(ctrl[23]),
        .FAB_WVALID(ctrl[24]),
        .FAB_BREADY(ctrl[25]),
        .FAB_ARLEN0(ctrl[26]),
        .FAB_ARLEN1(ctrl[27]),
        .FAB_ARLEN2(ctrl[28]),
        .FAB_ARLEN3(ctrl[29]),
        .FAB_ARLEN4(ctrl[30]),
        .FAB_ARLEN5(ctrl[31]),
        .FAB_ARLEN6(ctrl[32]),
        .FAB_ARLEN7(ctrl[33]),
        .FAB_ARSIZE0(ctrl[34]),
        .FAB_ARSIZE1(ctrl[35]),
        .FAB_ARSIZE2(ctrl[36]),
        .FAB_ARBURST0(ctrl[37]),
        .FAB_ARBURST1(ctrl[38]),
        .FAB_ARLOCK(ctrl[39]),
        .FAB_ARCACHE0(ctrl[40]),
        .FAB_ARCACHE1(ctrl[41]),
        .FAB_ARCACHE2(ctrl[42]),
        .FAB_ARCACHE3(ctrl[43]),
        .FAB_ARVALID(ctrl[44]),
        .FAB_RREADY(ctrl[45])
    );
endmodule
`resetall

`default_nettype none

// Functional test wrapper for the AXIL_S_IO_W supertile: AXIL_S_BEL at its
// master tile, looped back through axil_s_loopback.
// Test/axil_s_loopback_tb.v checks it from the SoC side.
module axil_s_loopback_top (output wire [66:0] o_out);
    wire [66:0] o;
    wire [40:0] i;

    axil_s_loopback logic_i (.o(o), .i(i));

    (* keep, BEL="X0Y16.A" *) AXIL_S_BEL axil_s_i (
        .FAB_AWADDR0(o[0]),
        .FAB_AWADDR1(o[1]),
        .FAB_AWADDR2(o[2]),
        .FAB_AWADDR3(o[3]),
        .FAB_AWADDR4(o[4]),
        .FAB_AWADDR5(o[5]),
        .FAB_AWADDR6(o[6]),
        .FAB_AWADDR7(o[7]),
        .FAB_AWADDR8(o[8]),
        .FAB_AWADDR9(o[9]),
        .FAB_AWPROT0(o[10]),
        .FAB_AWPROT1(o[11]),
        .FAB_AWPROT2(o[12]),
        .FAB_AWVALID(o[13]),
        .FAB_WDATA0(o[14]),
        .FAB_WDATA1(o[15]),
        .FAB_WDATA2(o[16]),
        .FAB_WDATA3(o[17]),
        .FAB_WDATA4(o[18]),
        .FAB_WDATA5(o[19]),
        .FAB_WDATA6(o[20]),
        .FAB_WDATA7(o[21]),
        .FAB_WDATA8(o[22]),
        .FAB_WDATA9(o[23]),
        .FAB_WDATA10(o[24]),
        .FAB_WDATA11(o[25]),
        .FAB_WDATA12(o[26]),
        .FAB_WDATA13(o[27]),
        .FAB_WDATA14(o[28]),
        .FAB_WDATA15(o[29]),
        .FAB_WDATA16(o[30]),
        .FAB_WDATA17(o[31]),
        .FAB_WDATA18(o[32]),
        .FAB_WDATA19(o[33]),
        .FAB_WDATA20(o[34]),
        .FAB_WDATA21(o[35]),
        .FAB_WDATA22(o[36]),
        .FAB_WDATA23(o[37]),
        .FAB_WDATA24(o[38]),
        .FAB_WDATA25(o[39]),
        .FAB_WDATA26(o[40]),
        .FAB_WDATA27(o[41]),
        .FAB_WDATA28(o[42]),
        .FAB_WDATA29(o[43]),
        .FAB_WDATA30(o[44]),
        .FAB_WDATA31(o[45]),
        .FAB_WSTRB0(o[46]),
        .FAB_WSTRB1(o[47]),
        .FAB_WSTRB2(o[48]),
        .FAB_WSTRB3(o[49]),
        .FAB_WVALID(o[50]),
        .FAB_BREADY(o[51]),
        .FAB_ARADDR0(o[52]),
        .FAB_ARADDR1(o[53]),
        .FAB_ARADDR2(o[54]),
        .FAB_ARADDR3(o[55]),
        .FAB_ARADDR4(o[56]),
        .FAB_ARADDR5(o[57]),
        .FAB_ARADDR6(o[58]),
        .FAB_ARADDR7(o[59]),
        .FAB_ARADDR8(o[60]),
        .FAB_ARADDR9(o[61]),
        .FAB_ARPROT0(o[62]),
        .FAB_ARPROT1(o[63]),
        .FAB_ARPROT2(o[64]),
        .FAB_ARVALID(o[65]),
        .FAB_RREADY(o[66]),
        .FAB_AWREADY(i[0]),
        .FAB_WREADY(i[1]),
        .FAB_BRESP0(i[2]),
        .FAB_BRESP1(i[3]),
        .FAB_BVALID(i[4]),
        .FAB_ARREADY(i[5]),
        .FAB_RDATA0(i[6]),
        .FAB_RDATA1(i[7]),
        .FAB_RDATA2(i[8]),
        .FAB_RDATA3(i[9]),
        .FAB_RDATA4(i[10]),
        .FAB_RDATA5(i[11]),
        .FAB_RDATA6(i[12]),
        .FAB_RDATA7(i[13]),
        .FAB_RDATA8(i[14]),
        .FAB_RDATA9(i[15]),
        .FAB_RDATA10(i[16]),
        .FAB_RDATA11(i[17]),
        .FAB_RDATA12(i[18]),
        .FAB_RDATA13(i[19]),
        .FAB_RDATA14(i[20]),
        .FAB_RDATA15(i[21]),
        .FAB_RDATA16(i[22]),
        .FAB_RDATA17(i[23]),
        .FAB_RDATA18(i[24]),
        .FAB_RDATA19(i[25]),
        .FAB_RDATA20(i[26]),
        .FAB_RDATA21(i[27]),
        .FAB_RDATA22(i[28]),
        .FAB_RDATA23(i[29]),
        .FAB_RDATA24(i[30]),
        .FAB_RDATA25(i[31]),
        .FAB_RDATA26(i[32]),
        .FAB_RDATA27(i[33]),
        .FAB_RDATA28(i[34]),
        .FAB_RDATA29(i[35]),
        .FAB_RDATA30(i[36]),
        .FAB_RDATA31(i[37]),
        .FAB_RRESP0(i[38]),
        .FAB_RRESP1(i[39]),
        .FAB_RVALID(i[40])
    );
    assign o_out = o;
endmodule
`resetall

`default_nettype none

// Functional test wrapper for SOC_DEBUG_IO: one SOC_DEBUG_CTRL_BEL per
// south-row column X1..X4, each with a different configuration, looped
// back through soc_debug_loopback. Test/soc_debug_loopback_tb.v checks it.
module soc_debug_loopback_top;
    wire [31:0] fab_dbg_out, fab_dbg_in;
    wire [3:0]  fab_rst_n, fab_irq;

    soc_debug_loopback logic_i (.fab_dbg_out(fab_dbg_out), .fab_rst_n(fab_rst_n),
                                .fab_dbg_in(fab_dbg_in), .fab_irq(fab_irq));

    (* keep, BEL="X1Y17.A" *) SOC_DEBUG_CTRL_BEL dbg0_i (
        .FAB_DEBUG_OUT0(fab_dbg_out[0]),
        .FAB_DEBUG_OUT1(fab_dbg_out[1]),
        .FAB_DEBUG_OUT2(fab_dbg_out[2]),
        .FAB_DEBUG_OUT3(fab_dbg_out[3]),
        .FAB_DEBUG_OUT4(fab_dbg_out[4]),
        .FAB_DEBUG_OUT5(fab_dbg_out[5]),
        .FAB_DEBUG_OUT6(fab_dbg_out[6]),
        .FAB_DEBUG_OUT7(fab_dbg_out[7]),
        .FAB_DEBUG_IN0(fab_dbg_in[0]),
        .FAB_DEBUG_IN1(fab_dbg_in[1]),
        .FAB_DEBUG_IN2(fab_dbg_in[2]),
        .FAB_DEBUG_IN3(fab_dbg_in[3]),
        .FAB_DEBUG_IN4(fab_dbg_in[4]),
        .FAB_DEBUG_IN5(fab_dbg_in[5]),
        .FAB_DEBUG_IN6(fab_dbg_in[6]),
        .FAB_DEBUG_IN7(fab_dbg_in[7]),
        .FAB_SLOT_SOFT_RST_N(fab_rst_n[0]),
        .FAB_USR_IRQ(fab_irq[0])
    );

    (* keep, BEL="X2Y17.A" *) SOC_DEBUG_CTRL_BEL #(.INV_RESET(1), .INV_IRQ(1)) dbg1_i (
        .FAB_DEBUG_OUT0(fab_dbg_out[8]),
        .FAB_DEBUG_OUT1(fab_dbg_out[9]),
        .FAB_DEBUG_OUT2(fab_dbg_out[10]),
        .FAB_DEBUG_OUT3(fab_dbg_out[11]),
        .FAB_DEBUG_OUT4(fab_dbg_out[12]),
        .FAB_DEBUG_OUT5(fab_dbg_out[13]),
        .FAB_DEBUG_OUT6(fab_dbg_out[14]),
        .FAB_DEBUG_OUT7(fab_dbg_out[15]),
        .FAB_DEBUG_IN0(fab_dbg_in[8]),
        .FAB_DEBUG_IN1(fab_dbg_in[9]),
        .FAB_DEBUG_IN2(fab_dbg_in[10]),
        .FAB_DEBUG_IN3(fab_dbg_in[11]),
        .FAB_DEBUG_IN4(fab_dbg_in[12]),
        .FAB_DEBUG_IN5(fab_dbg_in[13]),
        .FAB_DEBUG_IN6(fab_dbg_in[14]),
        .FAB_DEBUG_IN7(fab_dbg_in[15]),
        .FAB_SLOT_SOFT_RST_N(fab_rst_n[1]),
        .FAB_USR_IRQ(fab_irq[1])
    );

    (* keep, BEL="X3Y17.A" *) SOC_DEBUG_CTRL_BEL #(.BYPASS_RST(1), .BYPASS_IRQ(1)) dbg2_i (
        .FAB_DEBUG_OUT0(fab_dbg_out[16]),
        .FAB_DEBUG_OUT1(fab_dbg_out[17]),
        .FAB_DEBUG_OUT2(fab_dbg_out[18]),
        .FAB_DEBUG_OUT3(fab_dbg_out[19]),
        .FAB_DEBUG_OUT4(fab_dbg_out[20]),
        .FAB_DEBUG_OUT5(fab_dbg_out[21]),
        .FAB_DEBUG_OUT6(fab_dbg_out[22]),
        .FAB_DEBUG_OUT7(fab_dbg_out[23]),
        .FAB_DEBUG_IN0(fab_dbg_in[16]),
        .FAB_DEBUG_IN1(fab_dbg_in[17]),
        .FAB_DEBUG_IN2(fab_dbg_in[18]),
        .FAB_DEBUG_IN3(fab_dbg_in[19]),
        .FAB_DEBUG_IN4(fab_dbg_in[20]),
        .FAB_DEBUG_IN5(fab_dbg_in[21]),
        .FAB_DEBUG_IN6(fab_dbg_in[22]),
        .FAB_DEBUG_IN7(fab_dbg_in[23]),
        .FAB_SLOT_SOFT_RST_N(fab_rst_n[2]),
        .FAB_USR_IRQ(fab_irq[2])
    );

    (* keep, BEL="X4Y17.A" *) SOC_DEBUG_CTRL_BEL #(.INV_RESET(1), .INV_IRQ(1), .BYPASS_RST(1), .BYPASS_IRQ(1)) dbg3_i (
        .FAB_DEBUG_OUT0(fab_dbg_out[24]),
        .FAB_DEBUG_OUT1(fab_dbg_out[25]),
        .FAB_DEBUG_OUT2(fab_dbg_out[26]),
        .FAB_DEBUG_OUT3(fab_dbg_out[27]),
        .FAB_DEBUG_OUT4(fab_dbg_out[28]),
        .FAB_DEBUG_OUT5(fab_dbg_out[29]),
        .FAB_DEBUG_OUT6(fab_dbg_out[30]),
        .FAB_DEBUG_OUT7(fab_dbg_out[31]),
        .FAB_DEBUG_IN0(fab_dbg_in[24]),
        .FAB_DEBUG_IN1(fab_dbg_in[25]),
        .FAB_DEBUG_IN2(fab_dbg_in[26]),
        .FAB_DEBUG_IN3(fab_dbg_in[27]),
        .FAB_DEBUG_IN4(fab_dbg_in[28]),
        .FAB_DEBUG_IN5(fab_dbg_in[29]),
        .FAB_DEBUG_IN6(fab_dbg_in[30]),
        .FAB_DEBUG_IN7(fab_dbg_in[31]),
        .FAB_SLOT_SOFT_RST_N(fab_rst_n[3]),
        .FAB_USR_IRQ(fab_irq[3])
    );
endmodule
`resetall

`default_nettype none

// EXT_PMOD functional test 'bypass': EXT_PMOD_BEL at its master tile with
// the config bits under test, looped through the fabric logic.
module ext_pmod_bypass_top;
    wire [7:0]  fab_i, fab_o, fab_oe;
    wire [15:0] wdata;

    ext_pmod_bypass logic_i (.fab_i(fab_i), .wdata(wdata), .fab_o(fab_o), .fab_oe(fab_oe));

    (* keep, BEL="X2Y0.A" *) EXT_PMOD_BEL #(.BYPASS_IN_REG(1), .BYPASS_OUT_REG(1), .TIE_OFF_OE(1), .STATIC_OE(8'hA6), .OPEN_DRAIN_EN(1)) pmod_i (
        .FAB_PMOD_I0(fab_i[0]),
        .FAB_PMOD_I1(fab_i[1]),
        .FAB_PMOD_I2(fab_i[2]),
        .FAB_PMOD_I3(fab_i[3]),
        .FAB_PMOD_I4(fab_i[4]),
        .FAB_PMOD_I5(fab_i[5]),
        .FAB_PMOD_I6(fab_i[6]),
        .FAB_PMOD_I7(fab_i[7]),
        .FAB_PMOD_O0(fab_o[0]),
        .FAB_PMOD_O1(fab_o[1]),
        .FAB_PMOD_O2(fab_o[2]),
        .FAB_PMOD_O3(fab_o[3]),
        .FAB_PMOD_O4(fab_o[4]),
        .FAB_PMOD_O5(fab_o[5]),
        .FAB_PMOD_O6(fab_o[6]),
        .FAB_PMOD_O7(fab_o[7]),
        .FAB_PMOD_OE0(fab_oe[0]),
        .FAB_PMOD_OE1(fab_oe[1]),
        .FAB_PMOD_OE2(fab_oe[2]),
        .FAB_PMOD_OE3(fab_oe[3]),
        .FAB_PMOD_OE4(fab_oe[4]),
        .FAB_PMOD_OE5(fab_oe[5]),
        .FAB_PMOD_OE6(fab_oe[6]),
        .FAB_PMOD_OE7(fab_oe[7])
    );
    assign wdata = 16'b0;
endmodule
`resetall

`default_nettype none

// NPU_CTRL_CFG functional test 'skew_on': NPU_CTRL_CFG_BEL at its master
// tile, fed through the fabric from AXIL_S_BEL (the stimulus source).
module npu_ctrl_skew_on_top (input wire [66:0] o_in);
    wire [66:0] o = o_in;
    wire [36:0] i;

    npu_ctrl_skew_on logic_i (.o(o), .i(i));


    (* keep, BEL="X4Y0.A" *) NPU_CTRL_CFG_BEL #(.TIE_OFF_SKEW_EN(1)) npu_ctrl_i (
        .FAB_QUANT_SHIFT_IN0(i[0]),
        .FAB_QUANT_SHIFT_IN1(i[1]),
        .FAB_QUANT_SHIFT_IN2(i[2]),
        .FAB_QUANT_SHIFT_IN3(i[3]),
        .FAB_QUANT_SHIFT_IN4(i[4]),
        .FAB_QUANT_SHIFT_IN5(i[5]),
        .FAB_QUANT_SHIFT_IN6(i[6]),
        .FAB_QUANT_SHIFT_IN7(i[7]),
        .FAB_QUANT_SHIFT_IN8(i[8]),
        .FAB_QUANT_SHIFT_IN9(i[9]),
        .FAB_QUANT_SHIFT_IN10(i[10]),
        .FAB_QUANT_SHIFT_IN11(i[11]),
        .FAB_QUANT_SHIFT_IN12(i[12]),
        .FAB_QUANT_SHIFT_IN13(i[13]),
        .FAB_QUANT_SHIFT_IN14(i[14]),
        .FAB_QUANT_SHIFT_IN15(i[15]),
        .FAB_QUANT_SHIFT_IN16(i[16]),
        .FAB_QUANT_SHIFT_IN17(i[17]),
        .FAB_QUANT_SHIFT_IN18(i[18]),
        .FAB_QUANT_SHIFT_IN19(i[19]),
        .FAB_QUANT_SHIFT_IN20(i[20]),
        .FAB_QUANT_SHIFT_IN21(i[21]),
        .FAB_QUANT_SHIFT_IN22(i[22]),
        .FAB_QUANT_SHIFT_IN23(i[23]),
        .FAB_QUANT_SHIFT_IN24(i[24]),
        .FAB_QUANT_SHIFT_IN25(i[25]),
        .FAB_QUANT_SHIFT_IN26(i[26]),
        .FAB_QUANT_SHIFT_IN27(i[27]),
        .FAB_QUANT_SHIFT_IN28(i[28]),
        .FAB_QUANT_SHIFT_IN29(i[29]),
        .FAB_QUANT_SHIFT_EN(i[30]),
        .FAB_ARRAY_EN(i[31]),
        .FAB_PSUM_SYSTOLIC_EN(i[32]),
        .FAB_PSUM_LUT_EN(i[33]),
        .FAB_SWAP_WEIGHTS(i[34]),
        .FAB_PSUM_SKEW_EN(i[35]),
        .FAB_COMPUTE_BANK_SWAP(i[36])
    );
endmodule
`resetall

`default_nettype none

// NPU_ACCUM functional test: both NPU_ACCUM_SRAM_BELs at their master
// tiles (bank A north without write locks, bank B south with WRITE_LOCK),
// looped back through npu_accum_loopback.
module npu_accum_loopback_top;
    wire [31:0] ra, rb;
    wire [50:0] ia, ib;

    npu_accum_loopback logic_i (.ra(ra), .rb(rb), .ia(ia), .ib(ib));

    (* keep, BEL="X9Y0.A" *) NPU_ACCUM_SRAM_BEL bank_a_i (
        .FAB_RDATA0(ra[0]),
        .FAB_RDATA1(ra[1]),
        .FAB_RDATA2(ra[2]),
        .FAB_RDATA3(ra[3]),
        .FAB_RDATA4(ra[4]),
        .FAB_RDATA5(ra[5]),
        .FAB_RDATA6(ra[6]),
        .FAB_RDATA7(ra[7]),
        .FAB_RDATA8(ra[8]),
        .FAB_RDATA9(ra[9]),
        .FAB_RDATA10(ra[10]),
        .FAB_RDATA11(ra[11]),
        .FAB_RDATA12(ra[12]),
        .FAB_RDATA13(ra[13]),
        .FAB_RDATA14(ra[14]),
        .FAB_RDATA15(ra[15]),
        .FAB_RDATA16(ra[16]),
        .FAB_RDATA17(ra[17]),
        .FAB_RDATA18(ra[18]),
        .FAB_RDATA19(ra[19]),
        .FAB_RDATA20(ra[20]),
        .FAB_RDATA21(ra[21]),
        .FAB_RDATA22(ra[22]),
        .FAB_RDATA23(ra[23]),
        .FAB_RDATA24(ra[24]),
        .FAB_RDATA25(ra[25]),
        .FAB_RDATA26(ra[26]),
        .FAB_RDATA27(ra[27]),
        .FAB_RDATA28(ra[28]),
        .FAB_RDATA29(ra[29]),
        .FAB_RDATA30(ra[30]),
        .FAB_RDATA31(ra[31]),
        .FAB_ADDR0(ia[0]),
        .FAB_ADDR1(ia[1]),
        .FAB_ADDR2(ia[2]),
        .FAB_ADDR3(ia[3]),
        .FAB_ADDR4(ia[4]),
        .FAB_ADDR5(ia[5]),
        .FAB_ADDR6(ia[6]),
        .FAB_ADDR7(ia[7]),
        .FAB_WE0(ia[8]),
        .FAB_WE1(ia[9]),
        .FAB_WE2(ia[10]),
        .FAB_WE3(ia[11]),
        .FAB_WE4(ia[12]),
        .FAB_WE5(ia[13]),
        .FAB_WE6(ia[14]),
        .FAB_WE7(ia[15]),
        .FAB_WDATA0(ia[16]),
        .FAB_WDATA1(ia[17]),
        .FAB_WDATA2(ia[18]),
        .FAB_WDATA3(ia[19]),
        .FAB_WDATA4(ia[20]),
        .FAB_WDATA5(ia[21]),
        .FAB_WDATA6(ia[22]),
        .FAB_WDATA7(ia[23]),
        .FAB_WDATA8(ia[24]),
        .FAB_WDATA9(ia[25]),
        .FAB_WDATA10(ia[26]),
        .FAB_WDATA11(ia[27]),
        .FAB_WDATA12(ia[28]),
        .FAB_WDATA13(ia[29]),
        .FAB_WDATA14(ia[30]),
        .FAB_WDATA15(ia[31]),
        .FAB_WDATA16(ia[32]),
        .FAB_WDATA17(ia[33]),
        .FAB_WDATA18(ia[34]),
        .FAB_WDATA19(ia[35]),
        .FAB_WDATA20(ia[36]),
        .FAB_WDATA21(ia[37]),
        .FAB_WDATA22(ia[38]),
        .FAB_WDATA23(ia[39]),
        .FAB_WDATA24(ia[40]),
        .FAB_WDATA25(ia[41]),
        .FAB_WDATA26(ia[42]),
        .FAB_WDATA27(ia[43]),
        .FAB_WDATA28(ia[44]),
        .FAB_WDATA29(ia[45]),
        .FAB_WDATA30(ia[46]),
        .FAB_WDATA31(ia[47]),
        .FAB_READ_BANK_SEL0(ia[48]),
        .FAB_READ_BANK_SEL1(ia[49]),
        .FAB_READ_BANK_SEL2(ia[50])
    );

    (* keep, BEL="X9Y17.A" *) NPU_ACCUM_SRAM_BEL #(.WRITE_LOCK(8'h5A)) bank_b_i (
        .FAB_RDATA0(rb[0]),
        .FAB_RDATA1(rb[1]),
        .FAB_RDATA2(rb[2]),
        .FAB_RDATA3(rb[3]),
        .FAB_RDATA4(rb[4]),
        .FAB_RDATA5(rb[5]),
        .FAB_RDATA6(rb[6]),
        .FAB_RDATA7(rb[7]),
        .FAB_RDATA8(rb[8]),
        .FAB_RDATA9(rb[9]),
        .FAB_RDATA10(rb[10]),
        .FAB_RDATA11(rb[11]),
        .FAB_RDATA12(rb[12]),
        .FAB_RDATA13(rb[13]),
        .FAB_RDATA14(rb[14]),
        .FAB_RDATA15(rb[15]),
        .FAB_RDATA16(rb[16]),
        .FAB_RDATA17(rb[17]),
        .FAB_RDATA18(rb[18]),
        .FAB_RDATA19(rb[19]),
        .FAB_RDATA20(rb[20]),
        .FAB_RDATA21(rb[21]),
        .FAB_RDATA22(rb[22]),
        .FAB_RDATA23(rb[23]),
        .FAB_RDATA24(rb[24]),
        .FAB_RDATA25(rb[25]),
        .FAB_RDATA26(rb[26]),
        .FAB_RDATA27(rb[27]),
        .FAB_RDATA28(rb[28]),
        .FAB_RDATA29(rb[29]),
        .FAB_RDATA30(rb[30]),
        .FAB_RDATA31(rb[31]),
        .FAB_ADDR0(ib[0]),
        .FAB_ADDR1(ib[1]),
        .FAB_ADDR2(ib[2]),
        .FAB_ADDR3(ib[3]),
        .FAB_ADDR4(ib[4]),
        .FAB_ADDR5(ib[5]),
        .FAB_ADDR6(ib[6]),
        .FAB_ADDR7(ib[7]),
        .FAB_WE0(ib[8]),
        .FAB_WE1(ib[9]),
        .FAB_WE2(ib[10]),
        .FAB_WE3(ib[11]),
        .FAB_WE4(ib[12]),
        .FAB_WE5(ib[13]),
        .FAB_WE6(ib[14]),
        .FAB_WE7(ib[15]),
        .FAB_WDATA0(ib[16]),
        .FAB_WDATA1(ib[17]),
        .FAB_WDATA2(ib[18]),
        .FAB_WDATA3(ib[19]),
        .FAB_WDATA4(ib[20]),
        .FAB_WDATA5(ib[21]),
        .FAB_WDATA6(ib[22]),
        .FAB_WDATA7(ib[23]),
        .FAB_WDATA8(ib[24]),
        .FAB_WDATA9(ib[25]),
        .FAB_WDATA10(ib[26]),
        .FAB_WDATA11(ib[27]),
        .FAB_WDATA12(ib[28]),
        .FAB_WDATA13(ib[29]),
        .FAB_WDATA14(ib[30]),
        .FAB_WDATA15(ib[31]),
        .FAB_WDATA16(ib[32]),
        .FAB_WDATA17(ib[33]),
        .FAB_WDATA18(ib[34]),
        .FAB_WDATA19(ib[35]),
        .FAB_WDATA20(ib[36]),
        .FAB_WDATA21(ib[37]),
        .FAB_WDATA22(ib[38]),
        .FAB_WDATA23(ib[39]),
        .FAB_WDATA24(ib[40]),
        .FAB_WDATA25(ib[41]),
        .FAB_WDATA26(ib[42]),
        .FAB_WDATA27(ib[43]),
        .FAB_WDATA28(ib[44]),
        .FAB_WDATA29(ib[45]),
        .FAB_WDATA30(ib[46]),
        .FAB_WDATA31(ib[47]),
        .FAB_READ_BANK_SEL0(ib[48]),
        .FAB_READ_BANK_SEL1(ib[49]),
        .FAB_READ_BANK_SEL2(ib[50])
    );
endmodule
`resetall

`default_nettype none

// NPU_SLICE functional test: all 8 NPU_SLICE_DATA_SRAM_BELs at their
// master tiles, each with different config bits, looped back through
// npu_slice_loopback.
module npu_slice_loopback_top;
    wire [127:0] r;
    wire [247:0] i;

    npu_slice_loopback logic_i (.r(r), .i(i));

    (* keep, BEL="X10Y2.A" *) NPU_SLICE_DATA_SRAM_BEL slice0_i (
        .FAB_ACT_RDATA0(r[0]),
        .FAB_ACT_RDATA1(r[1]),
        .FAB_ACT_RDATA2(r[2]),
        .FAB_ACT_RDATA3(r[3]),
        .FAB_ACT_RDATA4(r[4]),
        .FAB_ACT_RDATA5(r[5]),
        .FAB_ACT_RDATA6(r[6]),
        .FAB_ACT_RDATA7(r[7]),
        .FAB_OUT_ACT0(r[8]),
        .FAB_OUT_ACT1(r[9]),
        .FAB_OUT_ACT2(r[10]),
        .FAB_OUT_ACT3(r[11]),
        .FAB_OUT_ACT4(r[12]),
        .FAB_OUT_ACT5(r[13]),
        .FAB_OUT_ACT6(r[14]),
        .FAB_OUT_ACT7(r[15]),
        .FAB_ACT_ADDR0(i[0]),
        .FAB_ACT_ADDR1(i[1]),
        .FAB_ACT_ADDR2(i[2]),
        .FAB_ACT_ADDR3(i[3]),
        .FAB_ACT_ADDR4(i[4]),
        .FAB_ACT_ADDR5(i[5]),
        .FAB_ACT_ADDR6(i[6]),
        .FAB_ACT_ADDR7(i[7]),
        .FAB_ACT_ADDR8(i[8]),
        .FAB_ACT_WDATA0(i[9]),
        .FAB_ACT_WDATA1(i[10]),
        .FAB_ACT_WDATA2(i[11]),
        .FAB_ACT_WDATA3(i[12]),
        .FAB_ACT_WDATA4(i[13]),
        .FAB_ACT_WDATA5(i[14]),
        .FAB_ACT_WDATA6(i[15]),
        .FAB_ACT_WDATA7(i[16]),
        .FAB_ACT_WE(i[17]),
        .FAB_WEIGHT_IN0(i[18]),
        .FAB_WEIGHT_IN1(i[19]),
        .FAB_WEIGHT_IN2(i[20]),
        .FAB_WEIGHT_IN3(i[21]),
        .FAB_WEIGHT_IN4(i[22]),
        .FAB_WEIGHT_IN5(i[23]),
        .FAB_WEIGHT_IN6(i[24]),
        .FAB_WEIGHT_IN7(i[25]),
        .FAB_WEIGHT_SHIFT_EN(i[26]),
        .FAB_XBAR_SEL0(i[27]),
        .FAB_XBAR_SEL1(i[28]),
        .FAB_XBAR_SEL2(i[29]),
        .FAB_XBAR_SEL3(i[30])
    );

    (* keep, BEL="X10Y4.A" *) NPU_SLICE_DATA_SRAM_BEL #(.FORCE_ZERO_XBAR(1)) slice1_i (
        .FAB_ACT_RDATA0(r[16]),
        .FAB_ACT_RDATA1(r[17]),
        .FAB_ACT_RDATA2(r[18]),
        .FAB_ACT_RDATA3(r[19]),
        .FAB_ACT_RDATA4(r[20]),
        .FAB_ACT_RDATA5(r[21]),
        .FAB_ACT_RDATA6(r[22]),
        .FAB_ACT_RDATA7(r[23]),
        .FAB_OUT_ACT0(r[24]),
        .FAB_OUT_ACT1(r[25]),
        .FAB_OUT_ACT2(r[26]),
        .FAB_OUT_ACT3(r[27]),
        .FAB_OUT_ACT4(r[28]),
        .FAB_OUT_ACT5(r[29]),
        .FAB_OUT_ACT6(r[30]),
        .FAB_OUT_ACT7(r[31]),
        .FAB_ACT_ADDR0(i[31]),
        .FAB_ACT_ADDR1(i[32]),
        .FAB_ACT_ADDR2(i[33]),
        .FAB_ACT_ADDR3(i[34]),
        .FAB_ACT_ADDR4(i[35]),
        .FAB_ACT_ADDR5(i[36]),
        .FAB_ACT_ADDR6(i[37]),
        .FAB_ACT_ADDR7(i[38]),
        .FAB_ACT_ADDR8(i[39]),
        .FAB_ACT_WDATA0(i[40]),
        .FAB_ACT_WDATA1(i[41]),
        .FAB_ACT_WDATA2(i[42]),
        .FAB_ACT_WDATA3(i[43]),
        .FAB_ACT_WDATA4(i[44]),
        .FAB_ACT_WDATA5(i[45]),
        .FAB_ACT_WDATA6(i[46]),
        .FAB_ACT_WDATA7(i[47]),
        .FAB_ACT_WE(i[48]),
        .FAB_WEIGHT_IN0(i[49]),
        .FAB_WEIGHT_IN1(i[50]),
        .FAB_WEIGHT_IN2(i[51]),
        .FAB_WEIGHT_IN3(i[52]),
        .FAB_WEIGHT_IN4(i[53]),
        .FAB_WEIGHT_IN5(i[54]),
        .FAB_WEIGHT_IN6(i[55]),
        .FAB_WEIGHT_IN7(i[56]),
        .FAB_WEIGHT_SHIFT_EN(i[57]),
        .FAB_XBAR_SEL0(i[58]),
        .FAB_XBAR_SEL1(i[59]),
        .FAB_XBAR_SEL2(i[60]),
        .FAB_XBAR_SEL3(i[61])
    );

    (* keep, BEL="X10Y6.A" *) NPU_SLICE_DATA_SRAM_BEL #(.STATIC_XBAR_EN(1), .STATIC_XBAR_VAL(3'b101)) slice2_i (
        .FAB_ACT_RDATA0(r[32]),
        .FAB_ACT_RDATA1(r[33]),
        .FAB_ACT_RDATA2(r[34]),
        .FAB_ACT_RDATA3(r[35]),
        .FAB_ACT_RDATA4(r[36]),
        .FAB_ACT_RDATA5(r[37]),
        .FAB_ACT_RDATA6(r[38]),
        .FAB_ACT_RDATA7(r[39]),
        .FAB_OUT_ACT0(r[40]),
        .FAB_OUT_ACT1(r[41]),
        .FAB_OUT_ACT2(r[42]),
        .FAB_OUT_ACT3(r[43]),
        .FAB_OUT_ACT4(r[44]),
        .FAB_OUT_ACT5(r[45]),
        .FAB_OUT_ACT6(r[46]),
        .FAB_OUT_ACT7(r[47]),
        .FAB_ACT_ADDR0(i[62]),
        .FAB_ACT_ADDR1(i[63]),
        .FAB_ACT_ADDR2(i[64]),
        .FAB_ACT_ADDR3(i[65]),
        .FAB_ACT_ADDR4(i[66]),
        .FAB_ACT_ADDR5(i[67]),
        .FAB_ACT_ADDR6(i[68]),
        .FAB_ACT_ADDR7(i[69]),
        .FAB_ACT_ADDR8(i[70]),
        .FAB_ACT_WDATA0(i[71]),
        .FAB_ACT_WDATA1(i[72]),
        .FAB_ACT_WDATA2(i[73]),
        .FAB_ACT_WDATA3(i[74]),
        .FAB_ACT_WDATA4(i[75]),
        .FAB_ACT_WDATA5(i[76]),
        .FAB_ACT_WDATA6(i[77]),
        .FAB_ACT_WDATA7(i[78]),
        .FAB_ACT_WE(i[79]),
        .FAB_WEIGHT_IN0(i[80]),
        .FAB_WEIGHT_IN1(i[81]),
        .FAB_WEIGHT_IN2(i[82]),
        .FAB_WEIGHT_IN3(i[83]),
        .FAB_WEIGHT_IN4(i[84]),
        .FAB_WEIGHT_IN5(i[85]),
        .FAB_WEIGHT_IN6(i[86]),
        .FAB_WEIGHT_IN7(i[87]),
        .FAB_WEIGHT_SHIFT_EN(i[88]),
        .FAB_XBAR_SEL0(i[89]),
        .FAB_XBAR_SEL1(i[90]),
        .FAB_XBAR_SEL2(i[91]),
        .FAB_XBAR_SEL3(i[92])
    );

    (* keep, BEL="X10Y8.A" *) NPU_SLICE_DATA_SRAM_BEL #(.FORCE_ZERO_XBAR(1), .STATIC_XBAR_EN(1), .STATIC_XBAR_VAL(3'b010)) slice3_i (
        .FAB_ACT_RDATA0(r[48]),
        .FAB_ACT_RDATA1(r[49]),
        .FAB_ACT_RDATA2(r[50]),
        .FAB_ACT_RDATA3(r[51]),
        .FAB_ACT_RDATA4(r[52]),
        .FAB_ACT_RDATA5(r[53]),
        .FAB_ACT_RDATA6(r[54]),
        .FAB_ACT_RDATA7(r[55]),
        .FAB_OUT_ACT0(r[56]),
        .FAB_OUT_ACT1(r[57]),
        .FAB_OUT_ACT2(r[58]),
        .FAB_OUT_ACT3(r[59]),
        .FAB_OUT_ACT4(r[60]),
        .FAB_OUT_ACT5(r[61]),
        .FAB_OUT_ACT6(r[62]),
        .FAB_OUT_ACT7(r[63]),
        .FAB_ACT_ADDR0(i[93]),
        .FAB_ACT_ADDR1(i[94]),
        .FAB_ACT_ADDR2(i[95]),
        .FAB_ACT_ADDR3(i[96]),
        .FAB_ACT_ADDR4(i[97]),
        .FAB_ACT_ADDR5(i[98]),
        .FAB_ACT_ADDR6(i[99]),
        .FAB_ACT_ADDR7(i[100]),
        .FAB_ACT_ADDR8(i[101]),
        .FAB_ACT_WDATA0(i[102]),
        .FAB_ACT_WDATA1(i[103]),
        .FAB_ACT_WDATA2(i[104]),
        .FAB_ACT_WDATA3(i[105]),
        .FAB_ACT_WDATA4(i[106]),
        .FAB_ACT_WDATA5(i[107]),
        .FAB_ACT_WDATA6(i[108]),
        .FAB_ACT_WDATA7(i[109]),
        .FAB_ACT_WE(i[110]),
        .FAB_WEIGHT_IN0(i[111]),
        .FAB_WEIGHT_IN1(i[112]),
        .FAB_WEIGHT_IN2(i[113]),
        .FAB_WEIGHT_IN3(i[114]),
        .FAB_WEIGHT_IN4(i[115]),
        .FAB_WEIGHT_IN5(i[116]),
        .FAB_WEIGHT_IN6(i[117]),
        .FAB_WEIGHT_IN7(i[118]),
        .FAB_WEIGHT_SHIFT_EN(i[119]),
        .FAB_XBAR_SEL0(i[120]),
        .FAB_XBAR_SEL1(i[121]),
        .FAB_XBAR_SEL2(i[122]),
        .FAB_XBAR_SEL3(i[123])
    );

    (* keep, BEL="X10Y10.A" *) NPU_SLICE_DATA_SRAM_BEL #(.WRITE_LOCK(1)) slice4_i (
        .FAB_ACT_RDATA0(r[64]),
        .FAB_ACT_RDATA1(r[65]),
        .FAB_ACT_RDATA2(r[66]),
        .FAB_ACT_RDATA3(r[67]),
        .FAB_ACT_RDATA4(r[68]),
        .FAB_ACT_RDATA5(r[69]),
        .FAB_ACT_RDATA6(r[70]),
        .FAB_ACT_RDATA7(r[71]),
        .FAB_OUT_ACT0(r[72]),
        .FAB_OUT_ACT1(r[73]),
        .FAB_OUT_ACT2(r[74]),
        .FAB_OUT_ACT3(r[75]),
        .FAB_OUT_ACT4(r[76]),
        .FAB_OUT_ACT5(r[77]),
        .FAB_OUT_ACT6(r[78]),
        .FAB_OUT_ACT7(r[79]),
        .FAB_ACT_ADDR0(i[124]),
        .FAB_ACT_ADDR1(i[125]),
        .FAB_ACT_ADDR2(i[126]),
        .FAB_ACT_ADDR3(i[127]),
        .FAB_ACT_ADDR4(i[128]),
        .FAB_ACT_ADDR5(i[129]),
        .FAB_ACT_ADDR6(i[130]),
        .FAB_ACT_ADDR7(i[131]),
        .FAB_ACT_ADDR8(i[132]),
        .FAB_ACT_WDATA0(i[133]),
        .FAB_ACT_WDATA1(i[134]),
        .FAB_ACT_WDATA2(i[135]),
        .FAB_ACT_WDATA3(i[136]),
        .FAB_ACT_WDATA4(i[137]),
        .FAB_ACT_WDATA5(i[138]),
        .FAB_ACT_WDATA6(i[139]),
        .FAB_ACT_WDATA7(i[140]),
        .FAB_ACT_WE(i[141]),
        .FAB_WEIGHT_IN0(i[142]),
        .FAB_WEIGHT_IN1(i[143]),
        .FAB_WEIGHT_IN2(i[144]),
        .FAB_WEIGHT_IN3(i[145]),
        .FAB_WEIGHT_IN4(i[146]),
        .FAB_WEIGHT_IN5(i[147]),
        .FAB_WEIGHT_IN6(i[148]),
        .FAB_WEIGHT_IN7(i[149]),
        .FAB_WEIGHT_SHIFT_EN(i[150]),
        .FAB_XBAR_SEL0(i[151]),
        .FAB_XBAR_SEL1(i[152]),
        .FAB_XBAR_SEL2(i[153]),
        .FAB_XBAR_SEL3(i[154])
    );

    (* keep, BEL="X10Y12.A" *) NPU_SLICE_DATA_SRAM_BEL #(.FORCE_ZERO_XBAR(1), .STATIC_XBAR_EN(1), .STATIC_XBAR_VAL(3'b111), .WRITE_LOCK(1)) slice5_i (
        .FAB_ACT_RDATA0(r[80]),
        .FAB_ACT_RDATA1(r[81]),
        .FAB_ACT_RDATA2(r[82]),
        .FAB_ACT_RDATA3(r[83]),
        .FAB_ACT_RDATA4(r[84]),
        .FAB_ACT_RDATA5(r[85]),
        .FAB_ACT_RDATA6(r[86]),
        .FAB_ACT_RDATA7(r[87]),
        .FAB_OUT_ACT0(r[88]),
        .FAB_OUT_ACT1(r[89]),
        .FAB_OUT_ACT2(r[90]),
        .FAB_OUT_ACT3(r[91]),
        .FAB_OUT_ACT4(r[92]),
        .FAB_OUT_ACT5(r[93]),
        .FAB_OUT_ACT6(r[94]),
        .FAB_OUT_ACT7(r[95]),
        .FAB_ACT_ADDR0(i[155]),
        .FAB_ACT_ADDR1(i[156]),
        .FAB_ACT_ADDR2(i[157]),
        .FAB_ACT_ADDR3(i[158]),
        .FAB_ACT_ADDR4(i[159]),
        .FAB_ACT_ADDR5(i[160]),
        .FAB_ACT_ADDR6(i[161]),
        .FAB_ACT_ADDR7(i[162]),
        .FAB_ACT_ADDR8(i[163]),
        .FAB_ACT_WDATA0(i[164]),
        .FAB_ACT_WDATA1(i[165]),
        .FAB_ACT_WDATA2(i[166]),
        .FAB_ACT_WDATA3(i[167]),
        .FAB_ACT_WDATA4(i[168]),
        .FAB_ACT_WDATA5(i[169]),
        .FAB_ACT_WDATA6(i[170]),
        .FAB_ACT_WDATA7(i[171]),
        .FAB_ACT_WE(i[172]),
        .FAB_WEIGHT_IN0(i[173]),
        .FAB_WEIGHT_IN1(i[174]),
        .FAB_WEIGHT_IN2(i[175]),
        .FAB_WEIGHT_IN3(i[176]),
        .FAB_WEIGHT_IN4(i[177]),
        .FAB_WEIGHT_IN5(i[178]),
        .FAB_WEIGHT_IN6(i[179]),
        .FAB_WEIGHT_IN7(i[180]),
        .FAB_WEIGHT_SHIFT_EN(i[181]),
        .FAB_XBAR_SEL0(i[182]),
        .FAB_XBAR_SEL1(i[183]),
        .FAB_XBAR_SEL2(i[184]),
        .FAB_XBAR_SEL3(i[185])
    );

    (* keep, BEL="X10Y14.A" *) NPU_SLICE_DATA_SRAM_BEL #(.STATIC_XBAR_EN(1), .STATIC_XBAR_VAL(3'b000)) slice6_i (
        .FAB_ACT_RDATA0(r[96]),
        .FAB_ACT_RDATA1(r[97]),
        .FAB_ACT_RDATA2(r[98]),
        .FAB_ACT_RDATA3(r[99]),
        .FAB_ACT_RDATA4(r[100]),
        .FAB_ACT_RDATA5(r[101]),
        .FAB_ACT_RDATA6(r[102]),
        .FAB_ACT_RDATA7(r[103]),
        .FAB_OUT_ACT0(r[104]),
        .FAB_OUT_ACT1(r[105]),
        .FAB_OUT_ACT2(r[106]),
        .FAB_OUT_ACT3(r[107]),
        .FAB_OUT_ACT4(r[108]),
        .FAB_OUT_ACT5(r[109]),
        .FAB_OUT_ACT6(r[110]),
        .FAB_OUT_ACT7(r[111]),
        .FAB_ACT_ADDR0(i[186]),
        .FAB_ACT_ADDR1(i[187]),
        .FAB_ACT_ADDR2(i[188]),
        .FAB_ACT_ADDR3(i[189]),
        .FAB_ACT_ADDR4(i[190]),
        .FAB_ACT_ADDR5(i[191]),
        .FAB_ACT_ADDR6(i[192]),
        .FAB_ACT_ADDR7(i[193]),
        .FAB_ACT_ADDR8(i[194]),
        .FAB_ACT_WDATA0(i[195]),
        .FAB_ACT_WDATA1(i[196]),
        .FAB_ACT_WDATA2(i[197]),
        .FAB_ACT_WDATA3(i[198]),
        .FAB_ACT_WDATA4(i[199]),
        .FAB_ACT_WDATA5(i[200]),
        .FAB_ACT_WDATA6(i[201]),
        .FAB_ACT_WDATA7(i[202]),
        .FAB_ACT_WE(i[203]),
        .FAB_WEIGHT_IN0(i[204]),
        .FAB_WEIGHT_IN1(i[205]),
        .FAB_WEIGHT_IN2(i[206]),
        .FAB_WEIGHT_IN3(i[207]),
        .FAB_WEIGHT_IN4(i[208]),
        .FAB_WEIGHT_IN5(i[209]),
        .FAB_WEIGHT_IN6(i[210]),
        .FAB_WEIGHT_IN7(i[211]),
        .FAB_WEIGHT_SHIFT_EN(i[212]),
        .FAB_XBAR_SEL0(i[213]),
        .FAB_XBAR_SEL1(i[214]),
        .FAB_XBAR_SEL2(i[215]),
        .FAB_XBAR_SEL3(i[216])
    );

    (* keep, BEL="X10Y16.A" *) NPU_SLICE_DATA_SRAM_BEL #(.FORCE_ZERO_XBAR(1), .WRITE_LOCK(1)) slice7_i (
        .FAB_ACT_RDATA0(r[112]),
        .FAB_ACT_RDATA1(r[113]),
        .FAB_ACT_RDATA2(r[114]),
        .FAB_ACT_RDATA3(r[115]),
        .FAB_ACT_RDATA4(r[116]),
        .FAB_ACT_RDATA5(r[117]),
        .FAB_ACT_RDATA6(r[118]),
        .FAB_ACT_RDATA7(r[119]),
        .FAB_OUT_ACT0(r[120]),
        .FAB_OUT_ACT1(r[121]),
        .FAB_OUT_ACT2(r[122]),
        .FAB_OUT_ACT3(r[123]),
        .FAB_OUT_ACT4(r[124]),
        .FAB_OUT_ACT5(r[125]),
        .FAB_OUT_ACT6(r[126]),
        .FAB_OUT_ACT7(r[127]),
        .FAB_ACT_ADDR0(i[217]),
        .FAB_ACT_ADDR1(i[218]),
        .FAB_ACT_ADDR2(i[219]),
        .FAB_ACT_ADDR3(i[220]),
        .FAB_ACT_ADDR4(i[221]),
        .FAB_ACT_ADDR5(i[222]),
        .FAB_ACT_ADDR6(i[223]),
        .FAB_ACT_ADDR7(i[224]),
        .FAB_ACT_ADDR8(i[225]),
        .FAB_ACT_WDATA0(i[226]),
        .FAB_ACT_WDATA1(i[227]),
        .FAB_ACT_WDATA2(i[228]),
        .FAB_ACT_WDATA3(i[229]),
        .FAB_ACT_WDATA4(i[230]),
        .FAB_ACT_WDATA5(i[231]),
        .FAB_ACT_WDATA6(i[232]),
        .FAB_ACT_WDATA7(i[233]),
        .FAB_ACT_WE(i[234]),
        .FAB_WEIGHT_IN0(i[235]),
        .FAB_WEIGHT_IN1(i[236]),
        .FAB_WEIGHT_IN2(i[237]),
        .FAB_WEIGHT_IN3(i[238]),
        .FAB_WEIGHT_IN4(i[239]),
        .FAB_WEIGHT_IN5(i[240]),
        .FAB_WEIGHT_IN6(i[241]),
        .FAB_WEIGHT_IN7(i[242]),
        .FAB_WEIGHT_SHIFT_EN(i[243]),
        .FAB_XBAR_SEL0(i[244]),
        .FAB_XBAR_SEL1(i[245]),
        .FAB_XBAR_SEL2(i[246]),
        .FAB_XBAR_SEL3(i[247])
    );
endmodule
`resetall

`default_nettype none

// Combined all-IO functional test: every IO BEL of the fabric in use at
// once. AXIL_S's fabric outputs also feed NPU_CTRL_CFG.
// Test/full_io_tb.v checks it.
module full_io_top;
    wire [66:0] axil_o;
    axi_m_loopback_top u_axi_m ();
    axil_s_loopback_top u_axil_s (.o_out(axil_o));
    soc_debug_loopback_top u_soc_debug ();
    ext_pmod_bypass_top u_ext_pmod ();
    npu_ctrl_skew_on_top u_npu_ctrl (.o_in(axil_o));
    npu_accum_loopback_top u_npu_accum ();
    npu_slice_loopback_top u_npu_slice ();
endmodule
`resetall
