`default_nettype none

// NPU_CTRL_CFG functional test 'skew_on': NPU_CTRL_CFG_BEL at its master
// tile, fed through the fabric from AXIL_S_BEL (the stimulus source).
module npu_ctrl_skew_on_top;
    wire [66:0] o;
    wire [36:0] i;

    npu_ctrl_skew_on logic_i (.o(o), .i(i));

    (* keep, BEL="X0Y16.A" *) AXIL_S_BEL axil_i (
        .FAB_AWADDR0(o[0]),
        .FAB_AWADDR1(o[1]),
        .FAB_AWADDR2(o[2]),
        .FAB_AWADDR3(o[3]),
        .FAB_AWADDR4(o[4]),
        .FAB_AWADDR5(o[5]),
        .FAB_AWADDR6(o[6]),
        .FAB_AWADDR7(o[7]),
        .FAB_AWADDR8(o[8]),
        .FAB_AWADDR9(o[9]),
        .FAB_AWPROT0(o[10]),
        .FAB_AWPROT1(o[11]),
        .FAB_AWPROT2(o[12]),
        .FAB_AWVALID(o[13]),
        .FAB_WDATA0(o[14]),
        .FAB_WDATA1(o[15]),
        .FAB_WDATA2(o[16]),
        .FAB_WDATA3(o[17]),
        .FAB_WDATA4(o[18]),
        .FAB_WDATA5(o[19]),
        .FAB_WDATA6(o[20]),
        .FAB_WDATA7(o[21]),
        .FAB_WDATA8(o[22]),
        .FAB_WDATA9(o[23]),
        .FAB_WDATA10(o[24]),
        .FAB_WDATA11(o[25]),
        .FAB_WDATA12(o[26]),
        .FAB_WDATA13(o[27]),
        .FAB_WDATA14(o[28]),
        .FAB_WDATA15(o[29]),
        .FAB_WDATA16(o[30]),
        .FAB_WDATA17(o[31]),
        .FAB_WDATA18(o[32]),
        .FAB_WDATA19(o[33]),
        .FAB_WDATA20(o[34]),
        .FAB_WDATA21(o[35]),
        .FAB_WDATA22(o[36]),
        .FAB_WDATA23(o[37]),
        .FAB_WDATA24(o[38]),
        .FAB_WDATA25(o[39]),
        .FAB_WDATA26(o[40]),
        .FAB_WDATA27(o[41]),
        .FAB_WDATA28(o[42]),
        .FAB_WDATA29(o[43]),
        .FAB_WDATA30(o[44]),
        .FAB_WDATA31(o[45]),
        .FAB_WSTRB0(o[46]),
        .FAB_WSTRB1(o[47]),
        .FAB_WSTRB2(o[48]),
        .FAB_WSTRB3(o[49]),
        .FAB_WVALID(o[50]),
        .FAB_BREADY(o[51]),
        .FAB_ARADDR0(o[52]),
        .FAB_ARADDR1(o[53]),
        .FAB_ARADDR2(o[54]),
        .FAB_ARADDR3(o[55]),
        .FAB_ARADDR4(o[56]),
        .FAB_ARADDR5(o[57]),
        .FAB_ARADDR6(o[58]),
        .FAB_ARADDR7(o[59]),
        .FAB_ARADDR8(o[60]),
        .FAB_ARADDR9(o[61]),
        .FAB_ARPROT0(o[62]),
        .FAB_ARPROT1(o[63]),
        .FAB_ARPROT2(o[64]),
        .FAB_ARVALID(o[65]),
        .FAB_RREADY(o[66])
    );

    (* keep, BEL="X4Y0.A" *) NPU_CTRL_CFG_BEL #(.TIE_OFF_SKEW_EN(1)) npu_ctrl_i (
        .FAB_QUANT_SHIFT_IN0(i[0]),
        .FAB_QUANT_SHIFT_IN1(i[1]),
        .FAB_QUANT_SHIFT_IN2(i[2]),
        .FAB_QUANT_SHIFT_IN3(i[3]),
        .FAB_QUANT_SHIFT_IN4(i[4]),
        .FAB_QUANT_SHIFT_IN5(i[5]),
        .FAB_QUANT_SHIFT_IN6(i[6]),
        .FAB_QUANT_SHIFT_IN7(i[7]),
        .FAB_QUANT_SHIFT_IN8(i[8]),
        .FAB_QUANT_SHIFT_IN9(i[9]),
        .FAB_QUANT_SHIFT_IN10(i[10]),
        .FAB_QUANT_SHIFT_IN11(i[11]),
        .FAB_QUANT_SHIFT_IN12(i[12]),
        .FAB_QUANT_SHIFT_IN13(i[13]),
        .FAB_QUANT_SHIFT_IN14(i[14]),
        .FAB_QUANT_SHIFT_IN15(i[15]),
        .FAB_QUANT_SHIFT_IN16(i[16]),
        .FAB_QUANT_SHIFT_IN17(i[17]),
        .FAB_QUANT_SHIFT_IN18(i[18]),
        .FAB_QUANT_SHIFT_IN19(i[19]),
        .FAB_QUANT_SHIFT_IN20(i[20]),
        .FAB_QUANT_SHIFT_IN21(i[21]),
        .FAB_QUANT_SHIFT_IN22(i[22]),
        .FAB_QUANT_SHIFT_IN23(i[23]),
        .FAB_QUANT_SHIFT_IN24(i[24]),
        .FAB_QUANT_SHIFT_IN25(i[25]),
        .FAB_QUANT_SHIFT_IN26(i[26]),
        .FAB_QUANT_SHIFT_IN27(i[27]),
        .FAB_QUANT_SHIFT_IN28(i[28]),
        .FAB_QUANT_SHIFT_IN29(i[29]),
        .FAB_QUANT_SHIFT_EN(i[30]),
        .FAB_ARRAY_EN(i[31]),
        .FAB_PSUM_SYSTOLIC_EN(i[32]),
        .FAB_PSUM_LUT_EN(i[33]),
        .FAB_SWAP_WEIGHTS(i[34]),
        .FAB_PSUM_SKEW_EN(i[35]),
        .FAB_COMPUTE_BANK_SWAP(i[36])
    );
endmodule
`resetall
